### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by padraicm** [suketa/ruby-duckdb#116]
This doesnt seem to work with the brew version of duckdb, and it's not obvious to me which of the install methods (https://duckdb.org/docs/installation/) this is intended to work with.

**Comment by suketa** [comment]
The ruby-duckdb requires duckdb.h of DuckDB. 
But duckdb.h is not installed by brew version of duckdb.
Try to install duckdb.h into `/usr/local/include` by yourself. 
The file `duckdb.h` is included in https://github.com/cwida/duckdb/releases/download/v0.2.2/libduckdb-osx-amd64.zip.
(C/C++ - Binary - macOS in https://duckdb.org/docs/installation/)
