### ISSUE TITLE
implement PreparedStatement#bind_time

### ISSUE THREAD

**Issue by suketa** [suketa/ruby-duckdb#250]
implement PreparedStatement#bind_time using by PreparedSatement#_bind_time private method.

```ruby
class Foo
  def to_str
    '01:01:00'
  end
end

require 'duckdb'
db = DuckDB::Database.open
con = db.connect
con.query('CREATE TABLE times (time_value TIME)')
...
stmt = DuckDB::PreparedStatement.new(con, 'SELECT * FROM dates WHERE time_value = $1')

stmt.bind_time(1, Time.now)
stmt.bind_time(1, '01:01:00')
stmt.bind_time(1, Foo.new)
```

**Comment by Ashvith** [comment]
Hey, I would like to check this issue. Could you share some more details about the same?

**Comment by Ashvith** [comment]
The above code wasn't working properly, so I made this snippet, if in case, anyone wants to try out:
```ruby
class Foo
  def to_str
    '01:01:00'
  end
end

require 'duckdb'
db = DuckDB::Database.open
con = db.connect
con.query("CREATE TABLE times (time_value TIME)")
now = Time.now
con.query("INSERT INTO times VALUES('#{now.hour}:#{now.min}:#{now.sec}')") 
con.query("SELECT * FROM times").each { |x| puts x }
stmt = DuckDB::PreparedStatement.new(con, 'SELECT * FROM times WHERE time_value = $1')
stmt.bind_time(1, now)
stmt.execute.each { |x| puts x }
```
After trial and error, it looks like the _bind_time() function in the C extension does not consider millisecond value, so I had to set that to zero.

**Comment by Ashvith** [comment]
After running the tests multiple times, looks like this wasn't still fixed

```bash
Error:
DuckDBTest::PreparedStatementTest#test__bind_time:
NoMethodError: undefined method `[]' for nil:NilClass
    /home/ashvith/Desktop/ruby-duckdb/test/duckdb_test/prepared_statement_test.rb:410:in `test__bind_time'


rails test home/ashvith/Desktop/ruby-duckdb/test/duckdb_test/prepared_statement_test.rb:400

.......................11:59:06.28781
expected #<DuckDB::Result:0x00000000025d2918>
2022-02-11 11:59:06.028781
```

This is probably caused by the `strftime` method. We have no option, but to divide by 1000.

**Comment by suketa** [comment]
Hmm, can we use `Time#usec` ?

**Comment by Ashvith** [comment]
@suketa still not working. I added this extra code snippet between the test method `test__bind_time` (line 405):

```ruby
      puts "\nExpected:\n#{now.strftime("%T.%6N")}"
      puts "\nActual:"
      puts "#{con.query("SELECT col_time FROM a").each{|x| puts x}}"
```

Also modified `self.now` with our the format that is making the error (line 22):
```ruby
    @now ||= Time.parse("2022-03-03 03:03:03.000110")
```

Output:
```bash
# Running:

........................................................
Expected:
03:03:03.000110

Actual:
03:03:03.11
#<DuckDB::Result:0x0000000002290250>
E

Error:
DuckDBTest::PreparedStatementTest#test__bind_time:
NoMethodError: undefined method `[]' for nil:NilClass
    /home/ashvith/Desktop/ruby-duckdb/test/duckdb_test/prepared_statement_test.rb:412:in `test__bind_time'


rails test home/ashvith/Desktop/ruby-duckdb/test/duckdb_test/prepared_statement_test.rb:397

........................................................
```

**Comment by suketa** [comment]
@Ashvith 
Does #277 solve our issue?

**Comment by suketa** [comment]
@Ashvith 

> still not working. I added this extra code snippet between the test method test__bind_time (line 405):

I'm very sorry, this is my fault. 
The database actual value should be `03:03:03.00011` 
I missed when test data inserting  https://github.com/suketa/ruby-duckdb/pull/277/files#diff-3ecc8f53a357e1774580cb9faac50a746b13fbccf168fd7b410e27e9139e8b8cR64

So, I think #277 solves this issue.

**Comment by Ashvith** [comment]
@suketa I would recommend that you avoid `Time.now` and instead use `Time.parse("2022-01-01 01:01:01.001100")` or something similar with millisecond having zeroes, because the chance of getting a zero in front is a pseudo-random event. The last commit you've shared introduces the same problem again.

Instead, can we change this?
https://github.com/suketa/ruby-duckdb/blob/43449714dd9eaf7895c32994fee61b79b8fd180d/ext/duckdb/util.c#L21

Is there a method like FLT2FLT or something? We can surely make use of that.
