### ISSUE TITLE
remove checking duckdb_appender_create in extconf.rb

### ISSUE THREAD

**Issue by suketa** [suketa/ruby-duckdb#302]
remove checking duckdb_appender_create in extconf.rb

We don't need to check duckdb_appender_create in extconf.rb any more because of dropping duckdb <= v0.2.8.

similar PR: https://github.com/suketa/ruby-duckdb/pull/290, https://github.com/suketa/ruby-duckdb/pull/289

**Comment by RishiKumarRay** [comment]
@suketa please review
