### ISSUE TITLE
A way to specify Unicode encoding

### ISSUE THREAD

**Issue by attilahorvath** [suketa/ruby-duckdb#370]
The strings in the result set always seem to be encoded as 8-bit ASCII, even when querying for UTF-8 values. Here is a minimal reproduction of the issue:

```ruby
require 'duckdb'

connection = DuckDB::Database.open.connect
result = connection.query("SELECT '😃' AS test")

puts result.first # => Encoding::UndefinedConversionError ("\xF0" from ASCII-8BIT to UTF-8)
```

I can force the encoding but that requires looping through the result set and manually setting it for each string value, which is a bit hacky. Something like:

```ruby
result_ary = result.to_a

result_ary.each do |row|
  row.select { |value| value.is_a?(String) }.each { |value| value.force_encoding(Encoding::UTF_8) }
end

puts result_ary.first # => 😃
```

This only works in simple cases though, it won't handle complex data types such as lists, although I haven't tested those.

It would be great if the encoding could be specified either when opening a connection for the entire session or separately for each query. Also, I think UTF-8 could be assumed as default because DuckDB is [storing texts in that encoding internally anyway](https://duckdb.org/docs/sql/data_types/text).

I can try to write a patch for this.

**Comment by suketa** [comment]
> I can try to write a patch for this.

Thank you for your reporting and trying to write patch.

**Comment by attilahorvath** [comment]
After some digging, it looks like DuckDB is always using UTF-8 anyway, so I don't think there is a need to allow any other encoding setting.

This PR simply changes the Ruby string encoding to UTF-8 everywhere and it seems to work well: #374.

**Comment by attilahorvath** [comment]
This is fixed now on `master`.
