### ISSUE TITLE
List Results are Always Nil

### ISSUE THREAD

**Issue by stephenprater** [suketa/ruby-duckdb#492]
When retrieving a list result from the DB, the results are always nil.

Minimal repro:

```
CREATE TABLE test (list INT[])
INSERT INTO test ([1,2])
SELECT * FROM test
```

Meanwhile in ruby land:

```ruby
c = DuckDB::Database.open('test.duckdb').connect
c.query('select * from test').to_a #=> [[nil]] - should be [1,2]
```

**Comment by suketa** [comment]
@stephenprater 

It is fixed by #659 only when `DuckDB::Result.use_chunk_each` is true (current default).
