### ISSUE TITLE
Homebrew install not working

### ISSUE THREAD

**Issue by mnovelo** [suketa/ruby-duckdb#561]
I'm posting an issue here to reference this issue https://github.com/duckdb/duckdb/issues/9611 regarding how the C++ headers are no longer included in the homebrew install. Without those C++ headers included in the homebrew install, you must install the headers manually for the appropriate version.

**Comment by mnovelo** [comment]
[The recommendation from the duckdb maintainers](https://github.com/duckdb/duckdb/issues/9611#issuecomment-1803498558) was to ship the requisite headers for DuckDB as part of this gem like sqlite3-ruby does. I've never done something like this, but I think I can create a PR that emulates what [sqlite3-ruby does](https://github.com/sparklemotion/sqlite3-ruby/blob/master/ext/sqlite3/extconf.rb)

I'll try working on that today since this has been a blocker for my team

**Comment by suketa** [comment]
@mnovelo 
Thank you.

I've not tried, but could you try mac-ports instead?
https://ports.macports.org/port/duckdb/details/

I found it includes the files used by ruby-duckdb.
ruby-duckdb uses duckdb.h and duckdb.dylib in MacOS.

https://build.macports.org/builders/ports-13_arm64-builder/builds/38445/steps/install-port/logs/files

It seems to me that sqlite3-ruby uses mac-ports version sqlite3 when building  native (precompiled) gems.

**Comment by carlopi** [comment]
Hi! Carlo from DuckDB, just got an updated duckdb version (v0.9.2) out, and while doing the PR to homebrew we decided to reintroduce headers and libraries.

This should hopefully solve this.

**Comment by mnovelo** [comment]
thank you so much @carlopi!
