### ISSUE TITLE
Memory leak reading parquet files

### ISSUE THREAD

**Issue by geclos** [suketa/ruby-duckdb#595]
Hi 👋🏼 

First of all thanks for your work, we make extensive use of ruby-duckdb at [Latitude](https://latitude.so).

We've encountered a memory leak when performing queries that read parquet files (e.g `SELECT * FROM read_parquet('foo.parquet')`), memory does not get freed after closing the database connection. Have you seen this before?

Thanks!

**Comment by suketa** [comment]
I have not read parquet files, and I have not seen it.
But I'll investigate it.

**Comment by mnovelo** [comment]
@geclos We read parquet files regularly and haven't seen this. What version of `duckdb` are you using, and have you been able to reproduce using one of `duckdb`'s other client APIs or with `duckdb`'s cli?

**Comment by geclos** [comment]
hey @mnovelo I'm not longer working on this so I haven't investigated further **but** I'm fairly confident this is not an issue of ruby-duckdb after all, so I will close this ticket.
