### ISSUE TITLE
Add example of using this with Ruby-on-Rails ActiveRecord to README

### ISSUE THREAD

**Issue by DeflateAwning** [suketa/ruby-duckdb#626]
Can you please add an example of using this with Ruby-on-Rails ActiveRecord to README, if it supports the ActiveRecord ORM?

**Comment by suketa** [comment]
ruby-duckdb does not support ActiveRecord by itself.
https://github.com/red-data-tools/activerecord-duckdb-adapter might be help. (I have not tried it yet.)

**Comment by DeflateAwning** [comment]
Thanks a lot, will check it out!
