### ISSUE TITLE
Unexpected async write to file on disconnect

### ISSUE THREAD

**Issue by fnorlin-skovik** [suketa/ruby-duckdb#775]
## What happens?

Hi,

We ran into the following issue where a DuckDB database file is not written when we expected it to be, after closing the connection to the database. It seems as if the write continue asynchronously after the close/disconnect methods has returned. Is this expected behaviour, and if so, are there any plans to implement a synchronous version?

## To Reproduce

Minimal reproducing example:

```ruby
require 'duckdb'

temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

con = DuckDB::Database.open(temp_file).connect

con.execute("CREATE TABLE test (id INTEGER)")
con.execute("INSERT INTO test VALUES (1), (2)")

file_last_saved = File.mtime(temp_file)

con.close

puts 'waiting for close' while file_last_saved == File.mtime(temp_file)

File.delete(temp_file)
```

Will result in lots of printed `waiting for close`, but will complete eventually.

## OS:
macOS: 14.6 (23G80)
## DuckDB version:
v1.1.1 af39bd0dcf
## ruby-duckdb version:
duckdb (1.1.1.0)
## Ruby version: 
ruby 3.2.4p170

**Comment by m-suketa** [comment]
Try `Database#close` after `Connection#close`.

```ruby
require 'duckdb'

temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

db = DuckDB::Database.open(temp_file)
con = db.connect

con.execute("CREATE TABLE test (id INTEGER)")
con.execute("INSERT INTO test VALUES (1), (2)")

file_last_saved = File.mtime(temp_file)

con.close
db.close

puts 'waiting for close' while file_last_saved == File.mtime(temp_file)

File.delete(temp_file)
```

**Comment by suketa** [comment]
Try `DuckDB::Database#close` after `DuckDB::Connection#close`.

```ruby
require 'duckdb'

temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

db = DuckDB::Database.open(temp_file)
con = db.connect

con.execute("CREATE TABLE test (id INTEGER)")
con.execute("INSERT INTO test VALUES (1), (2)")

file_last_saved = File.mtime(temp_file)

con.close
db.close

puts 'waiting for close' while file_last_saved == File.mtime(temp_file)

File.delete(temp_file)
```

**Comment by fnorlin-skovik** [comment]
That seems to work as long as you do not use prepared statements, but this example will produce the same problem again even if you do `DuckDB::Database#close` after `DuckDB::Connection#close`:

```ruby
require 'duckdb'

temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

db = DuckDB::Database.open(temp_file)
con = db.connect

con.execute("CREATE TABLE test (id INTEGER)")
con.execute("INSERT INTO test VALUES (?), (?)", 1, 2)

file_last_saved = File.mtime(temp_file)

con.close
db.close

puts 'waiting for close' while file_last_saved == File.mtime(temp_file)

File.delete(temp_file)
```

**Comment by suketa** [comment]
@fnorlin-skovik 
I close this issue. If you get any problem, create the new issue.
