### ISSUE TITLE
FATAL Error: Failed to create checkpoint because of error: Could not remove file data.duckdb.wal, No such file or directory (DuckDB::Error)

### ISSUE THREAD

**Issue by fnorlin-skovik** [suketa/ruby-duckdb#781]
## What happens?

Hi,

We have issues with DuckDB trying to delete a WAL-file that has already been deleted, and therefor crashes.

The issue is probably related to: https://github.com/suketa/ruby-duckdb/issues/775

## To Reproduce

Minimal reproducing example:

```ruby
require 'duckdb'

for wal_size in 9..2000
  puts "WAL Size: #{wal_size}"
  temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

  db = DuckDB::Database.open(temp_file)
  con = db.connect

  con.execute("SET checkpoint_threshold='#{wal_size}.0 B'")

  con.execute("CREATE TABLE test (id FLOAT)")

  for i in 1..5000
    con.execute("INSERT INTO test VALUES (?), (?)", 1, 2)
  end

  con.execute('CHECKPOINT')

  con.close
  db.close

  File.delete(temp_file)
end
```

Will result in approximately this (the program will crash around this point in time but the bug is not deterministic, more on that bellow):
```
WAL Size: 9
WAL Size: 10
/Users/xxx/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/duckdb-1.1.1.0/lib/duckdb/connection.rb:33:in `execute': FATAL Error: Failed to create checkpoint because of error: Could not remove file "/Users/xxx/repos/bugs/async-duckdb-write-bug/data.duckdb.wal": No such file or directory (DuckDB::Error)
	from /Users/xxx/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/duckdb-1.1.1.0/lib/duckdb/connection.rb:33:in `query'
	from wal.rb:15:in `block (2 levels) in <main>'
	from wal.rb:14:in `each'
	from wal.rb:14:in `block in <main>'
	from wal.rb:3:in `each'
	from wal.rb:3:in `<main>'
```

## Our investigation
We have researched this bug quite a lot in an effort to make it reproducible, and we are fairly certain that the issue has to do with the Ruby Garbage Collector.

E.g. disabling the garbage collector during execution seems to prevent the program from crashing, but is not a good solution:

```ruby
require 'duckdb'

for wal_size in 9..2000
  GC.disable
  puts "WAL Size: #{wal_size}"
  temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

  db = DuckDB::Database.open(temp_file)
  con = db.connect

  con.execute("SET checkpoint_threshold='#{wal_size}.0 B'")

  con.execute("CREATE TABLE test (id FLOAT)")

  for i in 1..5000
    con.execute("INSERT INTO test VALUES (?), (?)", 1, 2)
  end

  con.execute('CHECKPOINT')

  con.close
  db.close

  File.delete(temp_file)
  GC.enable
  GC.start
end
```

This should also be the reason that it is not possible to create a deterministic reproducible example, because the bug relies on the timing on which the Garbage collector is fired.

We can also add that explicitly running the garbage collector after closing the database and the connection seems to solve https://github.com/suketa/ruby-duckdb/issues/775, which is the reason we believe the issues are related.

## OS:
macOS: 14.6 (23G80)
## DuckDB version:
v1.1.1 af39bd0dcf
## ruby-duckdb version:
duckdb (1.1.1.0)
## Ruby version: 
ruby 3.2.4p170

**Comment by suketa** [comment]
I am investigating the issue, but I have not been able to fix it.

But I think we need only GC.start after DuckDB::Database#close and not GC.disable, GC.enable.

Could you check that the following code raises the same exception?

```ruby
require 'duckdb'

for wal_size in 9..2000
  puts "WAL Size: #{wal_size}"
  temp_file = "#{File.expand_path('.', __dir__)}/data.duckdb"

  db = DuckDB::Database.open(temp_file)
  con = db.connect

  con.execute("SET checkpoint_threshold='#{wal_size}.0 B'")

  con.execute("CREATE TABLE test (id FLOAT)")

  for i in 1..5000
    con.execute("INSERT INTO test VALUES (?), (?)", 1, 2)
  end

  con.execute('CHECKPOINT')

  con.close
  db.close
  GC.start

  File.delete(temp_file)
end
```

**Comment by suketa** [comment]
I hope https://github.com/suketa/ruby-duckdb/pull/783 will fix the issue and also #775.

Try ruby-duckdb v1.1.2.0.

**Comment by fnorlin-skovik** [comment]
Thank you!👍

Our initial tests indicate that #783 fixes both of our issues.

We will do further testing in the coming weeks, will get back to you if we’re able to reproduce any of these issues again.

**Comment by suketa** [comment]
@fnorlin-skovik 

I'll close this issue. If you get any of problem, create new issue.
